/**
 * generated by Xtext 2.21.0
 */
package org.group9.iOTConnector;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Filter Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.group9.iOTConnector.FilterExp#getReadingName <em>Reading Name</em>}</li>
 *   <li>{@link org.group9.iOTConnector.FilterExp#getRelationalOperator <em>Relational Operator</em>}</li>
 *   <li>{@link org.group9.iOTConnector.FilterExp#getNumber <em>Number</em>}</li>
 *   <li>{@link org.group9.iOTConnector.FilterExp#getBitwiseOperator <em>Bitwise Operator</em>}</li>
 *   <li>{@link org.group9.iOTConnector.FilterExp#getFilterExp <em>Filter Exp</em>}</li>
 * </ul>
 *
 * @see org.group9.iOTConnector.IOTConnectorPackage#getFilterExp()
 * @model
 * @generated
 */
public interface FilterExp extends EObject
{
  /**
   * Returns the value of the '<em><b>Reading Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reading Name</em>' containment reference.
   * @see #setReadingName(ReadingNameWithConfigScope)
   * @see org.group9.iOTConnector.IOTConnectorPackage#getFilterExp_ReadingName()
   * @model containment="true"
   * @generated
   */
  ReadingNameWithConfigScope getReadingName();

  /**
   * Sets the value of the '{@link org.group9.iOTConnector.FilterExp#getReadingName <em>Reading Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reading Name</em>' containment reference.
   * @see #getReadingName()
   * @generated
   */
  void setReadingName(ReadingNameWithConfigScope value);

  /**
   * Returns the value of the '<em><b>Relational Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relational Operator</em>' containment reference.
   * @see #setRelationalOperator(RelationalOperator)
   * @see org.group9.iOTConnector.IOTConnectorPackage#getFilterExp_RelationalOperator()
   * @model containment="true"
   * @generated
   */
  RelationalOperator getRelationalOperator();

  /**
   * Sets the value of the '{@link org.group9.iOTConnector.FilterExp#getRelationalOperator <em>Relational Operator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relational Operator</em>' containment reference.
   * @see #getRelationalOperator()
   * @generated
   */
  void setRelationalOperator(RelationalOperator value);

  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(int)
   * @see org.group9.iOTConnector.IOTConnectorPackage#getFilterExp_Number()
   * @model
   * @generated
   */
  int getNumber();

  /**
   * Sets the value of the '{@link org.group9.iOTConnector.FilterExp#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(int value);

  /**
   * Returns the value of the '<em><b>Bitwise Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bitwise Operator</em>' containment reference.
   * @see #setBitwiseOperator(BitwiseOperator)
   * @see org.group9.iOTConnector.IOTConnectorPackage#getFilterExp_BitwiseOperator()
   * @model containment="true"
   * @generated
   */
  BitwiseOperator getBitwiseOperator();

  /**
   * Sets the value of the '{@link org.group9.iOTConnector.FilterExp#getBitwiseOperator <em>Bitwise Operator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bitwise Operator</em>' containment reference.
   * @see #getBitwiseOperator()
   * @generated
   */
  void setBitwiseOperator(BitwiseOperator value);

  /**
   * Returns the value of the '<em><b>Filter Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filter Exp</em>' containment reference.
   * @see #setFilterExp(FilterExp)
   * @see org.group9.iOTConnector.IOTConnectorPackage#getFilterExp_FilterExp()
   * @model containment="true"
   * @generated
   */
  FilterExp getFilterExp();

  /**
   * Sets the value of the '{@link org.group9.iOTConnector.FilterExp#getFilterExp <em>Filter Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filter Exp</em>' containment reference.
   * @see #getFilterExp()
   * @generated
   */
  void setFilterExp(FilterExp value);

} // FilterExp
