/**
 * generated by Xtext 2.21.0
 */
package org.group9.iOTConnector;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.group9.iOTConnector.IOTConnectorPackage#getFunction()
 * @model
 * @generated
 */
public interface Function extends EObject
{
} // Function
