/**
 * generated by Xtext 2.21.0
 */
package org.group9.iOTConnector;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.group9.iOTConnector.ProcessAction#getReadingName <em>Reading Name</em>}</li>
 *   <li>{@link org.group9.iOTConnector.ProcessAction#getExp <em>Exp</em>}</li>
 * </ul>
 *
 * @see org.group9.iOTConnector.IOTConnectorPackage#getProcessAction()
 * @model
 * @generated
 */
public interface ProcessAction extends EObject
{
  /**
   * Returns the value of the '<em><b>Reading Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reading Name</em>' reference.
   * @see #setReadingName(ReadingName)
   * @see org.group9.iOTConnector.IOTConnectorPackage#getProcessAction_ReadingName()
   * @model
   * @generated
   */
  ReadingName getReadingName();

  /**
   * Sets the value of the '{@link org.group9.iOTConnector.ProcessAction#getReadingName <em>Reading Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reading Name</em>' reference.
   * @see #getReadingName()
   * @generated
   */
  void setReadingName(ReadingName value);

  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(Expression)
   * @see org.group9.iOTConnector.IOTConnectorPackage#getProcessAction_Exp()
   * @model containment="true"
   * @generated
   */
  Expression getExp();

  /**
   * Sets the value of the '{@link org.group9.iOTConnector.ProcessAction#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(Expression value);

} // ProcessAction
