/**
 * generated by Xtext 2.21.0
 */
package org.group9.iOTConnector;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.group9.iOTConnector.Process#getProcessActions <em>Process Actions</em>}</li>
 * </ul>
 *
 * @see org.group9.iOTConnector.IOTConnectorPackage#getProcess()
 * @model
 * @generated
 */
public interface Process extends Function
{
  /**
   * Returns the value of the '<em><b>Process Actions</b></em>' containment reference list.
   * The list contents are of type {@link org.group9.iOTConnector.ProcessAction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Process Actions</em>' containment reference list.
   * @see org.group9.iOTConnector.IOTConnectorPackage#getProcess_ProcessActions()
   * @model containment="true"
   * @generated
   */
  EList<ProcessAction> getProcessActions();

} // Process
