/**
 * generated by Xtext 2.21.0
 */
package org.group9.iOTConnector;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.group9.iOTConnector.Program#getWebserver <em>Webserver</em>}</li>
 *   <li>{@link org.group9.iOTConnector.Program#getWifis <em>Wifis</em>}</li>
 *   <li>{@link org.group9.iOTConnector.Program#getConfigs <em>Configs</em>}</li>
 *   <li>{@link org.group9.iOTConnector.Program#getBoards <em>Boards</em>}</li>
 * </ul>
 *
 * @see org.group9.iOTConnector.IOTConnectorPackage#getProgram()
 * @model
 * @generated
 */
public interface Program extends EObject
{
  /**
   * Returns the value of the '<em><b>Webserver</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Webserver</em>' containment reference.
   * @see #setWebserver(Webserver)
   * @see org.group9.iOTConnector.IOTConnectorPackage#getProgram_Webserver()
   * @model containment="true"
   * @generated
   */
  Webserver getWebserver();

  /**
   * Sets the value of the '{@link org.group9.iOTConnector.Program#getWebserver <em>Webserver</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Webserver</em>' containment reference.
   * @see #getWebserver()
   * @generated
   */
  void setWebserver(Webserver value);

  /**
   * Returns the value of the '<em><b>Wifis</b></em>' containment reference list.
   * The list contents are of type {@link org.group9.iOTConnector.Wifi}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wifis</em>' containment reference list.
   * @see org.group9.iOTConnector.IOTConnectorPackage#getProgram_Wifis()
   * @model containment="true"
   * @generated
   */
  EList<Wifi> getWifis();

  /**
   * Returns the value of the '<em><b>Configs</b></em>' containment reference list.
   * The list contents are of type {@link org.group9.iOTConnector.Config}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Configs</em>' containment reference list.
   * @see org.group9.iOTConnector.IOTConnectorPackage#getProgram_Configs()
   * @model containment="true"
   * @generated
   */
  EList<Config> getConfigs();

  /**
   * Returns the value of the '<em><b>Boards</b></em>' containment reference list.
   * The list contents are of type {@link org.group9.iOTConnector.Board}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Boards</em>' containment reference list.
   * @see org.group9.iOTConnector.IOTConnectorPackage#getProgram_Boards()
   * @model containment="true"
   * @generated
   */
  EList<Board> getBoards();

} // Program
