/**
 * generated by Xtext 2.21.0
 */
package org.group9.iOTConnector;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Send</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.group9.iOTConnector.Send#getSendActions <em>Send Actions</em>}</li>
 * </ul>
 *
 * @see org.group9.iOTConnector.IOTConnectorPackage#getSend()
 * @model
 * @generated
 */
public interface Send extends EObject
{
  /**
   * Returns the value of the '<em><b>Send Actions</b></em>' containment reference list.
   * The list contents are of type {@link org.group9.iOTConnector.SendAction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Send Actions</em>' containment reference list.
   * @see org.group9.iOTConnector.IOTConnectorPackage#getSend_SendActions()
   * @model containment="true"
   * @generated
   */
  EList<SendAction> getSendActions();

} // Send
