/**
 * generated by Xtext 2.21.0
 */
package org.group9.iOTConnector;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.group9.iOTConnector.Var#getReadingName <em>Reading Name</em>}</li>
 * </ul>
 *
 * @see org.group9.iOTConnector.IOTConnectorPackage#getVar()
 * @model
 * @generated
 */
public interface Var extends Expression
{
  /**
   * Returns the value of the '<em><b>Reading Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reading Name</em>' containment reference.
   * @see #setReadingName(ReadingNameWithConfigScope)
   * @see org.group9.iOTConnector.IOTConnectorPackage#getVar_ReadingName()
   * @model containment="true"
   * @generated
   */
  ReadingNameWithConfigScope getReadingName();

  /**
   * Sets the value of the '{@link org.group9.iOTConnector.Var#getReadingName <em>Reading Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reading Name</em>' containment reference.
   * @see #getReadingName()
   * @generated
   */
  void setReadingName(ReadingNameWithConfigScope value);

} // Var
