/*
 * generated by Xtext 2.21.0
 */
package org.group9.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIOTConnectorScopeProvider extends DelegatingScopeProvider {
}
