/*
 * generated by Xtext 2.21.0
 */
package org.group9.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class IOTConnectorAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/group9/parser/antlr/internal/InternalIOTConnector.tokens");
	}
}
