/*
 * generated by Xtext 2.21.0
 */
package org.group9.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.group9.parser.antlr.internal.InternalIOTConnectorParser;
import org.group9.services.IOTConnectorGrammarAccess;

public class IOTConnectorParser extends AbstractAntlrParser {

	@Inject
	private IOTConnectorGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalIOTConnectorParser createParser(XtextTokenStream stream) {
		return new InternalIOTConnectorParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public IOTConnectorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IOTConnectorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
