/*
 * generated by Xtext 2.21.0
 */
package org.group9;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IOTConnectorRuntimeModule extends AbstractIOTConnectorRuntimeModule {
}
