/*
 * generated by Xtext 2.21.0
 */
package org.group9;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class IOTConnectorStandaloneSetup extends IOTConnectorStandaloneSetupGenerated {

	public static void doSetup() {
		new IOTConnectorStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
