/*
 * generated by Xtext 2.21.0
 */
package org.group9.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class IOTConnectorUiModule extends AbstractIOTConnectorUiModule {

	public IOTConnectorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
