/*
 * generated by Xtext 2.21.0
 */
package org.group9.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.group9.IOTConnectorRuntimeModule;
import org.group9.IOTConnectorStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class IOTConnectorIdeSetup extends IOTConnectorStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new IOTConnectorRuntimeModule(), new IOTConnectorIdeModule()));
	}
	
}
