/*
 * generated by Xtext 2.21.0
 */
package org.group9.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.group9.IOTConnector.ui.internal.IOTConnectorActivator;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IOTConnectorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(IOTConnectorActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		IOTConnectorActivator activator = IOTConnectorActivator.getInstance();
		return activator != null ? activator.getInjector(IOTConnectorActivator.ORG_GROUP9_IOTCONNECTOR) : null;
	}

}
