/**
 * generated by Xtext 2.21.0
 */
package org.group9.iOTConnector.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.group9.iOTConnector.FilterAction;
import org.group9.iOTConnector.FilterExp;
import org.group9.iOTConnector.FilterType;
import org.group9.iOTConnector.IOTConnectorPackage;
import org.group9.iOTConnector.ReadingName;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Filter Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.group9.iOTConnector.impl.FilterActionImpl#getReadingName <em>Reading Name</em>}</li>
 *   <li>{@link org.group9.iOTConnector.impl.FilterActionImpl#getFilterType <em>Filter Type</em>}</li>
 *   <li>{@link org.group9.iOTConnector.impl.FilterActionImpl#getNumber <em>Number</em>}</li>
 *   <li>{@link org.group9.iOTConnector.impl.FilterActionImpl#getFilterExp <em>Filter Exp</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FilterActionImpl extends MinimalEObjectImpl.Container implements FilterAction
{
  /**
   * The cached value of the '{@link #getReadingName() <em>Reading Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReadingName()
   * @generated
   * @ordered
   */
  protected ReadingName readingName;

  /**
   * The cached value of the '{@link #getFilterType() <em>Filter Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFilterType()
   * @generated
   * @ordered
   */
  protected FilterType filterType;

  /**
   * The default value of the '{@link #getNumber() <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumber()
   * @generated
   * @ordered
   */
  protected static final int NUMBER_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNumber() <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumber()
   * @generated
   * @ordered
   */
  protected int number = NUMBER_EDEFAULT;

  /**
   * The cached value of the '{@link #getFilterExp() <em>Filter Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFilterExp()
   * @generated
   * @ordered
   */
  protected FilterExp filterExp;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FilterActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IOTConnectorPackage.Literals.FILTER_ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReadingName getReadingName()
  {
    if (readingName != null && readingName.eIsProxy())
    {
      InternalEObject oldReadingName = (InternalEObject)readingName;
      readingName = (ReadingName)eResolveProxy(oldReadingName);
      if (readingName != oldReadingName)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, IOTConnectorPackage.FILTER_ACTION__READING_NAME, oldReadingName, readingName));
      }
    }
    return readingName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ReadingName basicGetReadingName()
  {
    return readingName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReadingName(ReadingName newReadingName)
  {
    ReadingName oldReadingName = readingName;
    readingName = newReadingName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IOTConnectorPackage.FILTER_ACTION__READING_NAME, oldReadingName, readingName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FilterType getFilterType()
  {
    return filterType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFilterType(FilterType newFilterType, NotificationChain msgs)
  {
    FilterType oldFilterType = filterType;
    filterType = newFilterType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, IOTConnectorPackage.FILTER_ACTION__FILTER_TYPE, oldFilterType, newFilterType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFilterType(FilterType newFilterType)
  {
    if (newFilterType != filterType)
    {
      NotificationChain msgs = null;
      if (filterType != null)
        msgs = ((InternalEObject)filterType).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - IOTConnectorPackage.FILTER_ACTION__FILTER_TYPE, null, msgs);
      if (newFilterType != null)
        msgs = ((InternalEObject)newFilterType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - IOTConnectorPackage.FILTER_ACTION__FILTER_TYPE, null, msgs);
      msgs = basicSetFilterType(newFilterType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IOTConnectorPackage.FILTER_ACTION__FILTER_TYPE, newFilterType, newFilterType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getNumber()
  {
    return number;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNumber(int newNumber)
  {
    int oldNumber = number;
    number = newNumber;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IOTConnectorPackage.FILTER_ACTION__NUMBER, oldNumber, number));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FilterExp getFilterExp()
  {
    return filterExp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFilterExp(FilterExp newFilterExp, NotificationChain msgs)
  {
    FilterExp oldFilterExp = filterExp;
    filterExp = newFilterExp;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, IOTConnectorPackage.FILTER_ACTION__FILTER_EXP, oldFilterExp, newFilterExp);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFilterExp(FilterExp newFilterExp)
  {
    if (newFilterExp != filterExp)
    {
      NotificationChain msgs = null;
      if (filterExp != null)
        msgs = ((InternalEObject)filterExp).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - IOTConnectorPackage.FILTER_ACTION__FILTER_EXP, null, msgs);
      if (newFilterExp != null)
        msgs = ((InternalEObject)newFilterExp).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - IOTConnectorPackage.FILTER_ACTION__FILTER_EXP, null, msgs);
      msgs = basicSetFilterExp(newFilterExp, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IOTConnectorPackage.FILTER_ACTION__FILTER_EXP, newFilterExp, newFilterExp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case IOTConnectorPackage.FILTER_ACTION__FILTER_TYPE:
        return basicSetFilterType(null, msgs);
      case IOTConnectorPackage.FILTER_ACTION__FILTER_EXP:
        return basicSetFilterExp(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IOTConnectorPackage.FILTER_ACTION__READING_NAME:
        if (resolve) return getReadingName();
        return basicGetReadingName();
      case IOTConnectorPackage.FILTER_ACTION__FILTER_TYPE:
        return getFilterType();
      case IOTConnectorPackage.FILTER_ACTION__NUMBER:
        return getNumber();
      case IOTConnectorPackage.FILTER_ACTION__FILTER_EXP:
        return getFilterExp();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IOTConnectorPackage.FILTER_ACTION__READING_NAME:
        setReadingName((ReadingName)newValue);
        return;
      case IOTConnectorPackage.FILTER_ACTION__FILTER_TYPE:
        setFilterType((FilterType)newValue);
        return;
      case IOTConnectorPackage.FILTER_ACTION__NUMBER:
        setNumber((Integer)newValue);
        return;
      case IOTConnectorPackage.FILTER_ACTION__FILTER_EXP:
        setFilterExp((FilterExp)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IOTConnectorPackage.FILTER_ACTION__READING_NAME:
        setReadingName((ReadingName)null);
        return;
      case IOTConnectorPackage.FILTER_ACTION__FILTER_TYPE:
        setFilterType((FilterType)null);
        return;
      case IOTConnectorPackage.FILTER_ACTION__NUMBER:
        setNumber(NUMBER_EDEFAULT);
        return;
      case IOTConnectorPackage.FILTER_ACTION__FILTER_EXP:
        setFilterExp((FilterExp)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IOTConnectorPackage.FILTER_ACTION__READING_NAME:
        return readingName != null;
      case IOTConnectorPackage.FILTER_ACTION__FILTER_TYPE:
        return filterType != null;
      case IOTConnectorPackage.FILTER_ACTION__NUMBER:
        return number != NUMBER_EDEFAULT;
      case IOTConnectorPackage.FILTER_ACTION__FILTER_EXP:
        return filterExp != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (number: ");
    result.append(number);
    result.append(')');
    return result.toString();
  }

} //FilterActionImpl
